services:
  pdns:
    ports: !reset []
    networks:
      default:
        ipv4_address: "${PDNS_IPV4_ADDRESS}/${IPV4_NETMASK}"

  dnscrypt-proxy:
    networks:
      default:
        ipv4_address: "${DNSCRYPT_IPV4_ADDRESS}/${IPV4_NETMASK}"

  pdns-admin:
    ports: !reset []
    networks:
      default:
        ipv4_address: "${ADMIN_IPV4_ADDRESS}/${IPV4_NETMASK}"

networks:
  default:
    x-incus:
      ipv4.address: "${IPV4_GATEWAY}/${IPV4_NETMASK}"
    x-incus-compose:
      network: ${NETWORK}
