services:
  caddy:
    networks:
      default:
        x-incus:
          ipv4.address: ${IPV4_CADDY}
          ipv4.gateway: ${IPV4_GATEWAY}

networks:
  default:
    external: true
    x-incus-compose:
      network: ${EXTERNAL_NETWORK}
