workflow:
  auto_cancel:
    on_new_commit: interruptible
  rules:
    - if: $CI_COMMIT_TAG
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH
    - when: never

default:
  interruptible: true
  before_script:
    - mkdir -p "$GOPATH" "$GOBIN" "$GOCACHE"
    - cd "$CI_PROJECT_DIR"
  cache:
    key:
      files:
        - go.sum
      prefix: go
    paths:
      - .go/bin/
      - .go/cache/
      - .go/path/pkg/mod/

variables:
  GOPATH: "$CI_BUILDS_DIR/.go/path"
  GOBIN: "$CI_BUILDS_DIR/.go/bin"
  GOCACHE: "$CI_BUILDS_DIR/.go/cache"
  # https://stackoverflow.com/a/79780883/3368468
  GOTOOLCHAIN: "go1.26.0+auto"
  GIT_DEPTH: "0"
  REPORTS_DIR: reports

stages:
  - lint
  - test
  - test-custom
  - release

.non_release_rules:
  rules: &non_release_rules
    - if: $CI_COMMIT_TAG
      when: never
    - when: on_success

lint:
  stage: lint
  tags:
    - incus-compose-shell

  rules: *non_release_rules
  script:
    - go mod tidy -v -diff
    - golangci-lint run --output.code-climate.path=gl-code-quality-report.json
  artifacts:
    reports:
      codequality: gl-code-quality-report.json

test:
  stage: test
  tags:
    - incus-compose-shell

  rules: *non_release_rules
  variables:
    INCUS_REMOTE: ict
  script:
    - mkdir -p "$REPORTS_DIR"
    - go mod tidy -v -diff
    - go clean -testcache
    - set -o pipefail
    - NO_COLOR=1 go test ./... -parallel 1 -v -cover -coverprofile="$REPORTS_DIR/go-test-coverage.txt" 2>&1 | tee "$REPORTS_DIR/go-test-results.txt"
  after_script:
    - |
      if [[ -s "$REPORTS_DIR/go-test-results.txt" ]]; then
        go install github.com/jstemmer/go-junit-report/v2@latest
        "$GOBIN/go-junit-report" -in "$REPORTS_DIR/go-test-results.txt" -out "$REPORTS_DIR/junit.xml"
      fi
    - |
      if [[ -s "$REPORTS_DIR/go-test-coverage.txt" ]]; then
        go install gitlab.com/adiproject/gocover-report@latest
        "$GOBIN/gocover-report" -cobertura="$REPORTS_DIR/cobertura.xml" "$REPORTS_DIR/go-test-coverage.txt"
      fi
  coverage: '/^Total statement coverage: \d+(?:\.\d+)%/'
  artifacts:
    when: always
    expose_as: "go test reports"
    paths:
      - "$REPORTS_DIR"
    reports:
      junit: "$REPORTS_DIR/junit.xml"
      coverage_report:
        coverage_format: cobertura
        path: "$REPORTS_DIR/cobertura.xml"

test-custom:
  stage: test-custom
  tags:
    - incus-compose-shell

  rules: *non_release_rules
  variables:
    INCUS_REMOTE: ict-custom
  script:
    - mkdir -p "$REPORTS_DIR"
    - go mod tidy -v -diff
    - go clean -testcache
    - set -o pipefail
    - NO_COLOR=1 go test ./... -parallel 1 -v -cover -coverprofile="$REPORTS_DIR/go-test-coverage.txt" 2>&1 | tee "$REPORTS_DIR/go-test-results.txt"
  after_script:
    - |
      if [[ -s "$REPORTS_DIR/go-test-results.txt" ]]; then
        go install github.com/jstemmer/go-junit-report/v2@latest
        "$GOBIN/go-junit-report" -in "$REPORTS_DIR/go-test-results.txt" -out "$REPORTS_DIR/junit.xml"
      fi
    - |
      if [[ -s "$REPORTS_DIR/go-test-coverage.txt" ]]; then
        go install gitlab.com/adiproject/gocover-report@latest
        "$GOBIN/gocover-report" -cobertura="$REPORTS_DIR/cobertura.xml" "$REPORTS_DIR/go-test-coverage.txt"
      fi
  coverage: '/^Total statement coverage: \d+(?:\.\d+)%/'
  artifacts:
    when: always
    expose_as: "go test reports"
    paths:
      - "$REPORTS_DIR"
    reports:
      junit: "$REPORTS_DIR/junit.xml"
      coverage_report:
        coverage_format: cobertura
        path: "$REPORTS_DIR/cobertura.xml"
