default:
  tags:
    - linux
    - incus-compose-shell

stages:
  - lint
  - test

lint:
  stage: lint
  before_script:
    - cd $CI_PROJECT_DIR
  script:
    - golangci-lint run

test:
  stage: test
  variables:
    INCUS_REMOTE: ict
    REPORTS_DIR: reports
    GOPATH: $CI_BUILDS_DIR/.go/path
    GOBIN: $CI_BUILDS_DIR/.go/bin
    GOCACHE: $CI_BUILDS_DIR/.go/cache
    # https://stackoverflow.com/a/79780883/3368468
    GOTOOLCHAIN: go1.25.0+auto
  before_script:
    - mkdir -p "$GOPATH" "$GOBIN" "$GOCACHE"
    - cd "$CI_PROJECT_DIR"
    - mkdir "$REPORTS_DIR"
    - go mod tidy -v -diff
    - go clean -testcache
  script:
    - go test -v -cover -coverprofile="$REPORTS_DIR/go-test-coverage.txt" ./... 2>&1 | tee "$REPORTS_DIR/go-test-results.txt"
  after_script:
    - |
      # Convert Go test report to Junit format
      if [[ -s "$REPORTS_DIR/go-test-results.txt" ]]; then
        go install github.com/jstemmer/go-junit-report/v2@latest
        "$GOBIN/go-junit-report" -in "$REPORTS_DIR/go-test-results.txt" -out "$REPORTS_DIR/junit.xml"
      fi
    - |
      # Convert Go test coverage report to Cobertura format
      if [[ -s "$REPORTS_DIR/go-test-coverage.txt" ]]; then
        go install gitlab.com/adiproject/gocover-report@latest
        "$GOBIN/gocover-report" -cobertura="$REPORTS_DIR/cobertura.xml" "$REPORTS_DIR/go-test-coverage.txt"
      fi
  coverage: '/^Total statement coverage: \d+(?:\.\d+)%/'
  artifacts:
    expose_as: "go test reports"
    paths:
      - $REPORTS_DIR
    reports:
      junit: $REPORTS_DIR/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: $REPORTS_DIR/cobertura.xml
