# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

builds:
  - id: "incus-compose"
    main: ./cmd/incus-compose
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/lxc/incus-compose/cmd/incus-compose/version.Version={{ .Version }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

dockers_v2:
  - id: ic-healthd
    dockerfile: cmd/ic-healthd/Dockerfile.goreleaser
    build_args:
      VERSION: "{{ .Version }}"
    images:
      - "ghcr.io/lxc/incus-compose/ic-healthd"
    tags:
      - "{{ .Version }}"
    annotations:
      "org.opencontainers.image.description": "incus-compose - ic-healthd"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
    platforms:
      - linux/amd64
      - linux/arm64

release:
  footer: >-

    ---
    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
