services:
  wiki:
    ports: !reset []
    networks:
      default:
        ipv4_address: "${IPV4_ADDRESS}/${IPV4_NETMASK}"

networks:
  default:
    x-incus:
      ipv4.address: "${IPV4_GATEWAY}/${IPV4_NETMASK}"
    x-incus-compose:
      network: ${NETWORK}
