services:
  docker-registry:
    networks:
      default:
        ipv4_address: ${DOCKERIO_IPV4}/${IPV4_NETMASK}

  ghcr-registry:
    networks:
      default:
        ipv4_address: ${GHCRIO_IPV4}/${IPV4_NETMASK}

  gitlab-registry:
    networks:
      default:
        ipv4_address: ${GITLAB_IPV4}/${IPV4_NETMASK}

networks:
  default:
    x-incus:
      ipv4.address: ${GATEWAY_IPV4}/${IPV4_NETMASK}

volumes:
  docker:
    x-incus-compose:
      pool: ${STORAGE_POOL}
  ghcr:
    x-incus-compose:
      pool: ${STORAGE_POOL}
  gitlab:
    x-incus-compose:
      pool: ${STORAGE_POOL}
