FROM busybox:glibc

ARG TARGETPLATFORM
ARG APP_PATH=/usr/local/bin/ic-healthd
ARG VERSION

COPY ${TARGETPLATFORM}/ic-healthd ${APP_PATH}

USER 65534:65534
ENTRYPOINT ["/usr/local/bin/ic-healthd", "run"]
