services:
  database:
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready",
          "-U",
          "${POSTGRES_USER}",
          "-d",
          "${POSTGRES_DB}",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      # start_interval: 30s
      # start_period: 90s

  wiki:
    ports: !reset [] # do have static ip
    init: false # not supported
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      # start_interval: 30s
      # start_period: 90s
    networks:
      default:
        ipv4_address: 10.133.32.17

networks:
  default:
    x-incus:
      ipv4.nat: "true"
      ipv4.address: 10.133.32.1/24
