services:
  dnscrypt-proxy:
    image: klutchell/dnscrypt-proxy:main
    container_name: dnscrypt-proxy
    volumes:
      - ./dnscrypt-proxy:/config
      - dnscrypt.storage:/storage
    restart: unless-stopped

  knot:
    image: cznic/knot:v3.5.5
    container_name: knot
    command: -c knotd
    volumes:
      - ./knot/config:/config:ro
      - type: bind
        source: ./knot/storage
        target: /storage
        x-incus-compose:
          seed: true
    environment:
      TZ: "${TIMEZONE}"
    restart: "unless-stopped"
    healthcheck:
      test: ["CMD", "/usr/local/bin/dnsprobe", "google.com", "127.0.0.1:5053"]
      timeout: 1s
      interval: 5s
      retries: 6
      start_period: 1m

volumes:
  dnscrypt.storage:
